cloudnet-web:
  image: cloudnet
  env_file: .env.vmware-lab
  restart: always
  ports:
   - "443:3443"
  volumes:
   - .:/mnt/certs
  links:
   - cloudnet-redis
   - cloudnet-db
  command: foreman run web

cloudnet-worker:
  image: cloudnet
  env_file: .env.vmware-lab
  restart: always
  links:
   - cloudnet-redis
   - cloudnet-db
  command: foreman run sidekiq --logfile /dev/stdout

# Incomplete. Cron env doesn't get access to docker's env vars :(
# So hacked solution with RefreshAllServers.perform_async in ApplicationController
cloudnet-cron:
  image: cloudnet
  env_file: .env.vmware-lab
  restart: always
  volumes:
   - .env.vmware-lab:/app/env/.env
  links:
   - cloudnet-redis
   - cloudnet-db
  command: ./cron.sh
  
cloudnet-redis:
  image: redis

cloudnet-dbdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: "true"

cloudnet-db:
  image: postgres
  volumes_from:
    - cloudnet-dbdata
