defaults: &defaults
  maxmind:
    license_key: <%= ENV["MAXMIND_KEY"] %>
  five_hundred_px:
    api_key: <%= ENV["FIVEHUNDREDPX_KEY"] %>
  mapbox:
    token: <%= ENV["MAPBOX_TOKEN"] %>
    public_token: <%= ENV["MAPBOX_PUBLIC_TOKEN"] %>
  analytics:
    token: <%= ENV["ANALYTICS_KEY"] %>
  pingdom:
    api_key: <%= ENV["PINGDOM_KEY"] %>
    user: <%= ENV["PINGDOM_USER"] %>
    pass: <%= ENV["PINGDOM_PASS"] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
